### ISSUE TITLE
What should the message be ?

### ISSUE THREAD

**Issue by Fredo68usa** [IBM-Bluemix/python-hello-world-flask#6]
I installed locally this app. It worked VERY well. Thanks very much for that.

However, looking at the hello.py source, I was expecting to see the message from 

@app.route('/')
def hello_world():
    return 'Hello World! I am running on port ' + str(port)

But it's a more generic message that gets displayed, as if this hello_world() function was not executed like here:

(venv)[fpetit@oc7631104833 python-hello-world-flask]$ python hello.py
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
^C(venv)[fpetit@oc7631104833 python-hello-world-flask]$

**Comment by opiethehokie** [comment]
The app has been changed since this issue was opened, I don't think it applies anymore.
