### ISSUE TITLE
Path to vcap-local.json

### ISSUE THREAD

**Issue by tomyc** [IBM-Bluemix/python-hello-world-flask#9]
Hi,
Running locally the sample file vcap-local.json couldn't be find. So, my proposition is as follow:
...
elif os.path.isfile(os.path.join(os.path.dirname(__file__),'vcap-local.json')):
    with open(os.path.join(os.path.dirname(__file__),'vcap-local.json')) as f:
...
Best regards,
Tom

**Comment by opiethehokie** [comment]
@tomyc What OS are you on? The `vcap-local.json` file is found when the file is in the `get-started-python` directory for me on OSX.
